### ISSUE TITLE
Compile error / inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [tfausak/wuss#9]
See error below (due to an inaccurate version bound on `bytestring`, iirc `toStrict` was added to `bytestring-0.10`):

```
Configuring component lib from wuss-1.1.2
Preprocessing library wuss-1.1.2...
[1 of 2] Compiling Paths_wuss       ( /tmp/matrix-worker/1480475543/dist-newstyle/build/x86_64-linux/ghc-7.4.2/wuss-1.1.2/build/autogen/Paths_wuss.hs, /tmp/matrix-worker/1480475543/dist-newstyle/build/x86_64-linux/ghc-7.4.2/wuss-1.1.2/build/Paths_wuss.o )
[2 of 2] Compiling Wuss             ( Wuss.hs, /tmp/matrix-worker/1480475543/dist-newstyle/build/x86_64-linux/ghc-7.4.2/wuss-1.1.2/build/Wuss.o )

Wuss.hs:218:50:
    Not in scope: `LazyBytes.toStrict'
    Perhaps you meant `LazyBytes.interact' (imported from Data.ByteString.Lazy)
```

In case this is only a meta-data bug, you don't to upload a full release, you can simply fixup the meta-data via e.g.

- https://hackage.haskell.org/package/wuss-1.1.2/wuss.cabal/edit

or I can do it for you.

If you have any questions, please let me know!

**Comment by tfausak** [comment]
I'm impressed that your build plan included a version of bytestring <0.10. The latest 0.9 version was released in February 2012!

**Comment by tfausak** [comment]
Fixed by 766d334aeec7070076c4cd28256aa3a076f97103.

**Comment by hvr** [comment]
@tfausak it's what you get by default when you compile with GHC 7.4 or older :-)
